#!/bin/bash
gcc -Wall -ansi final2.c -o a.out -lm -O3
rm -r outputs
mkdir outputs
./a.out 2 outputs/data_2_0.csv
./a.out 2 outputs/data_2_1.csv
./a.out 2 outputs/data_2_2.csv
./a.out 2 outputs/data_2_3.csv
./a.out 2 outputs/data_2_4.csv
./a.out 2 outputs/data_2_5.csv
./a.out 2 outputs/data_2_6.csv
./a.out 2 outputs/data_2_7.csv
./a.out 2 outputs/data_2_8.csv
./a.out 2 outputs/data_2_9.csv
./a.out 3 outputs/data_3_0.csv
./a.out 3 outputs/data_3_1.csv
./a.out 3 outputs/data_3_2.csv
./a.out 3 outputs/data_3_3.csv
./a.out 3 outputs/data_3_4.csv
./a.out 3 outputs/data_3_5.csv
./a.out 3 outputs/data_3_6.csv
./a.out 3 outputs/data_3_7.csv
./a.out 3 outputs/data_3_8.csv
./a.out 3 outputs/data_3_9.csv
./a.out 4 outputs/data_4_0.csv
./a.out 4 outputs/data_4_1.csv
./a.out 4 outputs/data_4_2.csv
./a.out 4 outputs/data_4_3.csv
./a.out 4 outputs/data_4_4.csv
./a.out 4 outputs/data_4_5.csv
./a.out 4 outputs/data_4_6.csv
./a.out 4 outputs/data_4_7.csv
./a.out 4 outputs/data_4_8.csv
./a.out 4 outputs/data_4_9.csv
./a.out 5 outputs/data_5_0.csv
./a.out 5 outputs/data_5_1.csv
./a.out 5 outputs/data_5_2.csv
./a.out 5 outputs/data_5_3.csv
./a.out 5 outputs/data_5_4.csv
./a.out 5 outputs/data_5_5.csv
./a.out 5 outputs/data_5_6.csv
./a.out 5 outputs/data_5_7.csv
./a.out 5 outputs/data_5_8.csv
./a.out 5 outputs/data_5_9.csv
./a.out 6 outputs/data_6_0.csv
./a.out 6 outputs/data_6_1.csv
./a.out 6 outputs/data_6_2.csv
./a.out 6 outputs/data_6_3.csv
./a.out 6 outputs/data_6_4.csv
./a.out 6 outputs/data_6_5.csv
./a.out 6 outputs/data_6_6.csv
./a.out 6 outputs/data_6_7.csv
./a.out 6 outputs/data_6_8.csv
./a.out 6 outputs/data_6_9.csv
./a.out 7 outputs/data_7_0.csv
./a.out 7 outputs/data_7_1.csv
./a.out 7 outputs/data_7_2.csv
./a.out 7 outputs/data_7_3.csv
./a.out 7 outputs/data_7_4.csv
./a.out 7 outputs/data_7_5.csv
./a.out 7 outputs/data_7_6.csv
./a.out 7 outputs/data_7_7.csv
./a.out 7 outputs/data_7_8.csv
./a.out 7 outputs/data_7_9.csv
./a.out 8 outputs/data_8_0.csv
./a.out 8 outputs/data_8_1.csv
./a.out 8 outputs/data_8_2.csv
./a.out 8 outputs/data_8_3.csv
./a.out 8 outputs/data_8_4.csv
./a.out 8 outputs/data_8_5.csv
./a.out 8 outputs/data_8_6.csv
./a.out 8 outputs/data_8_7.csv
./a.out 8 outputs/data_8_8.csv
./a.out 8 outputs/data_8_9.csv
./a.out 9 outputs/data_9_0.csv
./a.out 9 outputs/data_9_1.csv
./a.out 9 outputs/data_9_2.csv
./a.out 9 outputs/data_9_3.csv
./a.out 9 outputs/data_9_4.csv
./a.out 9 outputs/data_9_5.csv
./a.out 9 outputs/data_9_6.csv
./a.out 9 outputs/data_9_7.csv
./a.out 9 outputs/data_9_8.csv
./a.out 9 outputs/data_9_9.csv
./a.out 10 outputs/data_10_0.csv
./a.out 10 outputs/data_10_1.csv
./a.out 10 outputs/data_10_2.csv
./a.out 10 outputs/data_10_3.csv
./a.out 10 outputs/data_10_4.csv
./a.out 10 outputs/data_10_5.csv
./a.out 10 outputs/data_10_6.csv
./a.out 10 outputs/data_10_7.csv
./a.out 10 outputs/data_10_8.csv
./a.out 10 outputs/data_10_9.csv
rm a.out
python3 final.py -a -d outputs/